### PR TITLE
Fixed bug with parallelTransition (in rare ocasions it finished witho…

### PR DESCRIPTION
**Pull request by jperedadnr**
…ut being executed none of the children transitions, and tiles in board were missplaced)

Fixed bug with layout overlay requested when it was already shown.

### CODE REVIEW

**Comment by brunoborges** [comment]
Thanks @jperedadnr  :-)

**Comment by jperedadnr** [comment]
I'm not sure if you will have the time to have a look at why parallelTransition as global field missed to execute some transitions in rare occasions. 

The parallel transition was created only once, and on every move we added some transitions, play it, wait for it to finish, and then clear the transitions and start all over again.

I've pushed it to the limit with AI algorithms and very short transitions (about 10 ms), and at some point I noticed that from time to time the parallel transition entered the finished handler, but none of its transitions were executed! This happened with more frequency on shorter transitions.

So by declaring a local parallel transition, I force to create a new one on every move, and now it doen't fail anymore...

**Comment by brunoborges** [comment]
But does it decrease overall performance? I wonder if this would look bad on a Raspberry Pi, for example

**Comment by jperedadnr** [comment]
I don't think so! Note that we already create on every move several SequenceTransitions and Timelines.

**Comment by brunoborges** [comment]
Alright!

**Pull request merged**
